
cards = {
    "Suit": {
        "Hearts":   '♡',
        "Spades":   '♤',
        "Stars":    '♢',
        "Clubs":    '♧',
    },
    "Deck": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 'J', 'Q', 'K', 'A']
}

objects = {
    "substance":                '>',
    "bin":                      '🗑',
    "number":                   '🔢',
    "sort":                     '🔁',
    "dataStructure":            '📚',
    "string":                   '🙱',
    "flag":                     '🚩',
    "timeData":                 '⏳',
    "path":                     '🖇',
    "file":                     '📄',
    "folder":                   '📁',
    "e_folder":                 '🗀',
    "d_folder":                 '📂',
    "element":                  '•',
    "video":                    '🎬',
    "slides":                   '🎟',
    "image":                    '🖻',
    "camera":                   '📷',
    "archive":                  '💾',
    "game":                     "🎮",
    "CG":                       '📛',
    "system":                   '🗔',
    "audio":                    '🎵',
    "guitar":                   '🎸',
    "piano":                    '🎹',
    "arrow_r":                  '🢤',
    "arrow":                    '➠',
    "arrow_broken":             '⭍',
    "net":                      '🖧',
    "cloth":                    '👗',
    "log":                      '📜',
    "draw":                     '🎨',
    "texture":                  '🌀',
    "font":                     '🗛',
    "vector":                   '❐',
    "play":                     '▶',
    "map":                      '📊',
    "settings":                 '🔧',
    "text":                     '📝',
    "table":                    '📅',
    "phone":                    '📱',
    "castle":                   '🏰',
    "house":                    '🕋',
    "code":                     '💻',
    "clip":                     '🔗',
    "people":                   '👥',
    "link":                     '⮬',
    "windows":                  '🗗',
    "grid":                     '▤',
    "bye":                      '🚪',
    "question":                 '❓',
    "vfx":                      '🎆',
    "dragon":                   '🐉',
}
